### Why Pandas?

- Flexibility of python
- Working with big data files

<b>Load data into pandas</b>

In [45]:
import pandas as pd

df = pd.read_csv(r'pokemon.csv')

#print(df.head(10))

In [2]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [5]:
df.tail(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [6]:
df.head(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False

In [7]:
# Read a excel file

df_xlsx = pd.read_excel('Movies1.xlsx')

In [8]:
df_xlsx

     Rank                Movie Name  Year of Release  IMDB Rating
0       1  The Shawshank Redemption             1994          9.2
1       2             The Godfather             1972          9.2
2       3           The Dark Knight             2008          9.0
3       4     The Godfather Part II             1974          9.0
4       5              12 Angry Men             1957          9.0
..    ...                       ...              ...          ...
245   246               Dersu Uzala             1975          8.0
246   247                  The Help             2011          8.0
247   248                   Aladdin             1992          8.0
248   249                    Gandhi             1982          8.0
249   250        Dances with Wolves             1990          8.0

[250 rows x 4 columns]

In [ ]:
# Read a txt file
df_txt = pd.read_csv('demo.txt',delimiter="\t")

<b>Reading Data in Pandas</b>

In [9]:
#Reading Headers
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [12]:
#Read
df['Name']

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [17]:
print(df[['Name','Type 1']])

                      Name   Type 1
0                Bulbasaur    Grass
1                  Ivysaur    Grass
2                 Venusaur    Grass
3    VenusaurMega Venusaur    Grass
4               Charmander     Fire
..                     ...      ...
795                Diancie     Rock
796    DiancieMega Diancie     Rock
797    HoopaHoopa Confined  Psychic
798     HoopaHoopa Unbound  Psychic
799              Volcanion     Fire

[800 rows x 2 columns]

In [19]:
#Read Each row
df.iloc[1]

#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
Total             405
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object

In [24]:
for index,row in df.iterrows():
    print(index, row['Name'])

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 CharizardMega Charizard X
8 CharizardMega Charizard Y
9 Squirtle
10 Wartortle
11 Blastoise
12 BlastoiseMega Blastoise
13 Caterpie
14 Metapod
15 Butterfree
16 Weedle
17 Kakuna
18 Beedrill
19 BeedrillMega Beedrill
20 Pidgey
21 Pidgeotto
22 Pidgeot
23 PidgeotMega Pidgeot
24 Rattata
25 Raticate
26 Spearow
27 Fearow
28 Ekans
29 Arbok
30 Pikachu
31 Raichu
32 Sandshrew
33 Sandslash
34 Nidoranâ™€
35 Nidorina
36 Nidoqueen
37 Nidoranâ™‚
38 Nidorino
39 Nidoking
40 Clefairy
41 Clefable
42 Vulpix
43 Ninetales
44 Jigglypuff
45 Wigglytuff
46 Zubat
47 Golbat
48 Oddish
49 Gloom
50 Vileplume
51 Paras
52 Parasect
53 Venonat
54 Venomoth
55 Diglett
56 Dugtrio
57 Meowth
58 Persian
59 Psyduck
60 Golduck
61 Mankey
62 Primeape
63 Growlithe
64 Arcanine
65 Poliwag
66 Poliwhirl
67 Poliwrath
68 Abra
69 Kadabra
70 Alakazam
71 AlakazamMega Alakazam
72 Machop
73 Machoke
74 Machamp
75 Bellsprout
76 Weepinbell
77 Victreebel
78 Tentacool
79 Tentacruel
80 Geodude
81 Graveler
82 Golem
83 Ponyta
84 Rapidash
85 Slowpoke
86 Slowbro
87 SlowbroMega Slowbro
88 Magnemite
89 Magneton
90 Farfetch'd
91 Doduo
92 Dodrio
93 Seel
94 Dewgong
95 Grimer
96 Muk
97 Shellder
98 Cloyster
99 Gastly
100 Haunter
101 Gengar
102 GengarMega Gengar
103 Onix
104 Drowzee
105 Hypno
106 Krabby
107 Kingler
108 Voltorb
109 Electrode
110 Exeggcute
111 Exeggutor
112 Cubone
113 Marowak
114 Hitmonlee
115 Hitmonchan
116 Lickitung
117 Koffing
118 Weezing
119 Rhyhorn
120 Rhydon
121 Chansey
122 Tangela
123 Kangaskhan
124 KangaskhanMega Kangaskhan
125 Horsea
126 Seadra
127 Goldeen
128 Seaking
129 Staryu
130 Starmie
131 Mr. Mime
132 Scyther
133 Jynx
134 Electabuzz
135 Magmar
136 Pinsir
137 PinsirMega Pinsir
138 Tauros
139 Magikarp
140 Gyarados
141 GyaradosMega Gyarados
142 Lapras
143 Ditto
144 Eevee
145 Vaporeon
146 Jolteon
147 Flareon
148 Porygon
149 Omanyte
150 Omastar
151 Kabuto
152 Kabutops
153 Aerodactyl
154 AerodactylMega Aerodactyl
155 Snorlax
156 Articuno
157 Zapdos
158 Moltres
159 Dratini
160 Dragonair
161 Dragonite
162 Mewtwo
163 MewtwoMega Mewtwo X
164 MewtwoMega Mewtwo Y
165 Mew
166 Chikorita
167 Bayleef
168 Meganium
169 Cyndaquil
170 Quilava
171 Typhlosion
172 Totodile
173 Croconaw
174 Feraligatr
175 Sentret
176 Furret
177 Hoothoot
178 Noctowl
179 Ledyba
180 Ledian
181 Spinarak
182 Ariados
183 Crobat
184 Chinchou
185 Lanturn
186 Pichu
187 Cleffa
188 Igglybuff
189 Togepi
190 Togetic
191 Natu
192 Xatu
193 Mareep
194 Flaaffy
195 Ampharos
196 AmpharosMega Ampharos
197 Bellossom
198 Marill
199 Azumarill
200 Sudowoodo
201 Politoed
202 Hoppip
203 Skiploom
204 Jumpluff
205 Aipom
206 Sunkern
207 Sunflora
208 Yanma
209 Wooper
210 Quagsire
211 Espeon
212 Umbreon
213 Murkrow
214 Slowking
215 Misdreavus
216 Unown
217 Wobbuffet
218 Girafarig
219 Pineco
220 Forretress
221 Dunsparce
222 Gligar
223 Steelix
224 SteelixMega Steelix
225 Snubbull
226 Granbull
227 Qwilfish
228 Scizor
229 ScizorMega Scizor
230 Shuckle
231 Heracross
232 HeracrossMega Heracross
233 Sneasel
234 Teddiursa
235 Ursaring
236 Slugma
237 Magcargo
238 Swinub
239 Piloswine
240 Corsola
241 Remoraid
242 Octillery
243 Delibird
244 Mantine
245 Skarmory
246 Houndour
247 Houndoom
248 HoundoomMega Houndoom
249 Kingdra
250 Phanpy
251 Donphan
252 Porygon2
253 Stantler
254 Smeargle
255 Tyrogue
256 Hitmontop
257 Smoochum
258 Elekid
259 Magby
260 Miltank
261 Blissey
262 Raikou
263 Entei
264 Suicune
265 Larvitar
266 Pupitar
267 Tyranitar
268 TyranitarMega Tyranitar
269 Lugia
270 Ho-oh
271 Celebi
272 Treecko
273 Grovyle
274 Sceptile
275 SceptileMega Sceptile
276 Torchic
277 Combusken
278 Blaziken
279 BlazikenMega Blaziken
280 Mudkip
281 Marshtomp
282 Swampert
283 SwampertMega Swampert
284 Poochyena
285 Mightyena
286 Zigzagoon
287 Linoone
288 Wurmple
289 Silcoon
290 Beautifly
291 Cascoon
292 Dustox
293 Lotad
294 Lombre
295 Ludicolo
296 Seedot
297 Nuzleaf
298 Shiftry
299 Taillow
300 Swellow
301 Wingull
302 Pelipper
303 Ralts
304 Kirlia
305 Gardevoir
306 GardevoirMega Gardevoir
307 Surskit
308 Masquerain
309 Shroomish
310 Breloom
311 Slakoth
312 Vigoroth
313 Slaking
314 Nincada
315 Ninjask
316 Shedinja
317 Whismur
318 Loudred
319 Exploud
320 Makuhita
321 Hariyama
322 Azurill
323 Nosepass
324 Skitty
325 Delcatty
326 Sableye
327 SableyeMega Sableye
328 Mawile
329 MawileMega Mawile
330 Aron
331 Lairon
332 Aggron
333 AggronMega Aggron
334 Meditite
335 Medicham
336 MedichamMega Medicham
337 Electrike
338 Manectric
339 ManectricMega Manectric
340 Plusle
341 Minun
342 Volbeat
343 Illumise
344 Roselia
345 Gulpin
346 Swalot
347 Carvanha
348 Sharpedo
349 SharpedoMega Sharpedo
350 Wailmer
351 Wailord
352 Numel
353 Camerupt
354 CameruptMega Camerupt
355 Torkoal
356 Spoink
357 Grumpig
358 Spinda
359 Trapinch
360 Vibrava
361 Flygon
362 Cacnea
363 Cacturne
364 Swablu
365 Altaria
366 AltariaMega Altaria
367 Zangoose
368 Seviper
369 Lunatone
370 Solrock
371 Barboach
372 Whiscash
373 Corphish
374 Crawdaunt
375 Baltoy
376 Claydol
377 Lileep
378 Cradily
379 Anorith
380 Armaldo
381 Feebas
382 Milotic
383 Castform
384 Kecleon
385 Shuppet
386 Banette
387 BanetteMega Banette
388 Duskull
389 Dusclops
390 Tropius
391 Chimecho
392 Absol
393 AbsolMega Absol
394 Wynaut
395 Snorunt
396 Glalie
397 GlalieMega Glalie
398 Spheal
399 Sealeo
400 Walrein
401 Clamperl
402 Huntail
403 Gorebyss
404 Relicanth
405 Luvdisc
406 Bagon
407 Shelgon
408 Salamence
409 SalamenceMega Salamence
410 Beldum
411 Metang
412 Metagross
413 MetagrossMega Metagross
414 Regirock
415 Regice
416 Registeel
417 Latias
418 LatiasMega Latias
419 Latios
420 LatiosMega Latios
421 Kyogre
422 KyogrePrimal Kyogre
423 Groudon
424 GroudonPrimal Groudon
425 Rayquaza
426 RayquazaMega Rayquaza
427 Jirachi
428 DeoxysNormal Forme
429 DeoxysAttack Forme
430 DeoxysDefense Forme
431 DeoxysSpeed Forme
432 Turtwig
433 Grotle
434 Torterra
435 Chimchar
436 Monferno
437 Infernape
438 Piplup
439 Prinplup
440 Empoleon
441 Starly
442 Staravia
443 Staraptor
444 Bidoof
445 Bibarel
446 Kricketot
447 Kricketune
448 Shinx
449 Luxio
450 Luxray
451 Budew
452 Roserade
453 Cranidos
454 Rampardos
455 Shieldon
456 Bastiodon
457 Burmy
458 WormadamPlant Cloak
459 WormadamSandy Cloak
460 WormadamTrash Cloak
461 Mothim
462 Combee
463 Vespiquen
464 Pachirisu
465 Buizel
466 Floatzel
467 Cherubi
468 Cherrim
469 Shellos
470 Gastrodon
471 Ambipom
472 Drifloon
473 Drifblim
474 Buneary
475 Lopunny
476 LopunnyMega Lopunny
477 Mismagius
478 Honchkrow
479 Glameow
480 Purugly
481 Chingling
482 Stunky
483 Skuntank
484 Bronzor
485 Bronzong
486 Bonsly
487 Mime Jr.
488 Happiny
489 Chatot
490 Spiritomb
491 Gible
492 Gabite
493 Garchomp
494 GarchompMega Garchomp
495 Munchlax
496 Riolu
497 Lucario
498 LucarioMega Lucario
499 Hippopotas
500 Hippowdon
501 Skorupi
502 Drapion
503 Croagunk
504 Toxicroak
505 Carnivine
506 Finneon
507 Lumineon
508 Mantyke
509 Snover
510 Abomasnow
511 AbomasnowMega Abomasnow
512 Weavile
513 Magnezone
514 Lickilicky
515 Rhyperior
516 Tangrowth
517 Electivire
518 Magmortar
519 Togekiss
520 Yanmega
521 Leafeon
522 Glaceon
523 Gliscor
524 Mamoswine
525 Porygon-Z
526 Gallade
527 GalladeMega Gallade
528 Probopass
529 Dusknoir
530 Froslass
531 Rotom
532 RotomHeat Rotom
533 RotomWash Rotom
534 RotomFrost Rotom
535 RotomFan Rotom
536 RotomMow Rotom
537 Uxie
538 Mesprit
539 Azelf
540 Dialga
541 Palkia
542 Heatran
543 Regigigas
544 GiratinaAltered Forme
545 GiratinaOrigin Forme
546 Cresselia
547 Phione
548 Manaphy
549 Darkrai
550 ShayminLand Forme
551 ShayminSky Forme
552 Arceus
553 Victini
554 Snivy
555 Servine
556 Serperior
557 Tepig
558 Pignite
559 Emboar
560 Oshawott
561 Dewott
562 Samurott
563 Patrat
564 Watchog
565 Lillipup
566 Herdier
567 Stoutland
568 Purrloin
569 Liepard
570 Pansage
571 Simisage
572 Pansear
573 Simisear
574 Panpour
575 Simipour
576 Munna
577 Musharna
578 Pidove
579 Tranquill
580 Unfezant
581 Blitzle
582 Zebstrika
583 Roggenrola
584 Boldore
585 Gigalith
586 Woobat
587 Swoobat
588 Drilbur
589 Excadrill
590 Audino
591 AudinoMega Audino
592 Timburr
593 Gurdurr
594 Conkeldurr
595 Tympole
596 Palpitoad
597 Seismitoad
598 Throh
599 Sawk
600 Sewaddle
601 Swadloon
602 Leavanny
603 Venipede
604 Whirlipede
605 Scolipede
606 Cottonee
607 Whimsicott
608 Petilil
609 Lilligant
610 Basculin
611 Sandile
612 Krokorok
613 Krookodile
614 Darumaka
615 DarmanitanStandard Mode
616 DarmanitanZen Mode
617 Maractus
618 Dwebble
619 Crustle
620 Scraggy
621 Scrafty
622 Sigilyph
623 Yamask
624 Cofagrigus
625 Tirtouga
626 Carracosta
627 Archen
628 Archeops
629 Trubbish
630 Garbodor
631 Zorua
632 Zoroark
633 Minccino
634 Cinccino
635 Gothita
636 Gothorita
637 Gothitelle
638 Solosis
639 Duosion
640 Reuniclus
641 Ducklett
642 Swanna
643 Vanillite
644 Vanillish
645 Vanilluxe
646 Deerling
647 Sawsbuck
648 Emolga
649 Karrablast
650 Escavalier
651 Foongus
652 Amoonguss
653 Frillish
654 Jellicent
655 Alomomola
656 Joltik
657 Galvantula
658 Ferroseed
659 Ferrothorn
660 Klink
661 Klang
662 Klinklang
663 Tynamo
664 Eelektrik
665 Eelektross
666 Elgyem
667 Beheeyem
668 Litwick
669 Lampent
670 Chandelure
671 Axew
672 Fraxure
673 Haxorus
674 Cubchoo
675 Beartic
676 Cryogonal
677 Shelmet
678 Accelgor
679 Stunfisk
680 Mienfoo
681 Mienshao
682 Druddigon
683 Golett
684 Golurk
685 Pawniard
686 Bisharp
687 Bouffalant
688 Rufflet
689 Braviary
690 Vullaby
691 Mandibuzz
692 Heatmor
693 Durant
694 Deino
695 Zweilous
696 Hydreigon
697 Larvesta
698 Volcarona
699 Cobalion
700 Terrakion
701 Virizion
702 TornadusIncarnate Forme
703 TornadusTherian Forme
704 ThundurusIncarnate Forme
705 ThundurusTherian Forme
706 Reshiram
707 Zekrom
708 LandorusIncarnate Forme
709 LandorusTherian Forme
710 Kyurem
711 KyuremBlack Kyurem
712 KyuremWhite Kyurem
713 KeldeoOrdinary Forme
714 KeldeoResolute Forme
715 MeloettaAria Forme
716 MeloettaPirouette Forme
717 Genesect
718 Chespin
719 Quilladin
720 Chesnaught
721 Fennekin
722 Braixen
723 Delphox
724 Froakie
725 Frogadier
726 Greninja
727 Bunnelby
728 Diggersby
729 Fletchling
730 Fletchinder
731 Talonflame
732 Scatterbug
733 Spewpa
734 Vivillon
735 Litleo
736 Pyroar
737 FlabÃ©bÃ©
738 Floette
739 Florges
740 Skiddo
741 Gogoat
742 Pancham
743 Pangoro
744 Furfrou
745 Espurr
746 MeowsticMale
747 MeowsticFemale
748 Honedge
749 Doublade
750 AegislashBlade Forme
751 AegislashShield Forme
752 Spritzee
753 Aromatisse
754 Swirlix
755 Slurpuff
756 Inkay
757 Malamar
758 Binacle
759 Barbaracle
760 Skrelp
761 Dragalge
762 Clauncher
763 Clawitzer
764 Helioptile
765 Heliolisk
766 Tyrunt
767 Tyrantrum
768 Amaura
769 Aurorus
770 Sylveon
771 Hawlucha
772 Dedenne
773 Carbink
774 Goomy
775 Sliggoo
776 Goodra
777 Klefki
778 Phantump
779 Trevenant
780 PumpkabooAverage Size
781 PumpkabooSmall Size
782 PumpkabooLarge Size
783 PumpkabooSuper Size
784 GourgeistAverage Size
785 GourgeistSmall Size
786 GourgeistLarge Size
787 GourgeistSuper Size
788 Bergmite
789 Avalugg
790 Noibat
791 Noivern
792 Xerneas
793 Yveltal
794 Zygarde50% Forme
795 Diancie
796 DiancieMega Diancie
797 HoopaHoopa Confined
798 HoopaHoopa Unbound
799 Volcanion

In [20]:
df.iloc[1:4]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False

In [21]:
#Read a specific location(R,C)

df.iloc[2,1]

'Venusaur'

In [25]:
df.loc[df['Type 1'] == "Fire"]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,505,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,350,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,410,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,500,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,495,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,525,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,309,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,405,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,534,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,250,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,410,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,365,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,580,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,310,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,405,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,530,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,305,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,460,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,470,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,309,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,405,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,534,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,540,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,600,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,308,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,528,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,316,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,498,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,315,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,480,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,484,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,307,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,409,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,534,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,382,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,499,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,369,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

### Sorting and Describing data

In [26]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [31]:
#df.sort_values('Name')
#df.sort_values('Name',ascending=False)
#df.sort_values(['Name','Type 1'],ascending=False)
df.sort_values(['Name','Type 1'],ascending=[1,0])

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,494,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,330,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,420,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True

### Making changes to the data

In [32]:
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [37]:
#Adding a new column
df['Total1'] = df['Total']+df['HP']+df['Attack']

In [38]:
df['Total1'].head()

0    506
1    649
2    849
3    985
4    491
Name: Total1, dtype: int64

In [40]:
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total1
0,1,Bulbasaur,Grass,Poison,412,45,49,49,65,65,45,1,False,506
1,2,Ivysaur,Grass,Poison,527,60,62,63,80,80,60,1,False,649
2,3,Venusaur,Grass,Poison,687,80,82,83,100,100,80,1,False,849
3,3,VenusaurMega Venusaur,Grass,Poison,805,80,100,123,122,120,80,1,False,985
4,4,Charmander,Fire,NaN,400,39,52,43,60,50,65,1,False,491

In [41]:
#dropping a column

df.drop(columns=['Total','Total1'])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [45]:
df['Total']=df.iloc[:,4:10].sum(axis=1)

In [44]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total1
0,1,Bulbasaur,Grass,Poison,620,45,49,49,65,65,45,1,False,506
1,2,Ivysaur,Grass,Poison,792,60,62,63,80,80,60,1,False,649
2,3,Venusaur,Grass,Poison,1032,80,82,83,100,100,80,1,False,849
3,3,VenusaurMega Venusaur,Grass,Poison,1230,80,100,123,122,120,80,1,False,985
4,4,Charmander,Fire,NaN,594,39,52,43,60,50,65,1,False,491
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,1150,50,100,150,100,150,50,6,True,900
796,719,DiancieMega Diancie,Rock,Fairy,1390,50,160,110,160,110,110,6,True,1120
797,720,HoopaHoopa Confined,Psychic,Ghost,1190,80,110,60,150,130,70,6,True,980
798,720,HoopaHoopa Unbound,Psychic,Dark,1390,80,160,60,170,130,80,6,True,1160
799,721,Volcanion,Fire,Water,1230,80,110,120,130,90,70,6,True,980

In [49]:
cols=list(df.columns.values)
df= df [cols[0:4]+[cols[-1]]+ cols[4:]]

In [51]:
df.head()

,#,Name,Type 1,Type 2,Total1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total1
0,1,Bulbasaur,Grass,Poison,506,893,45,49,49,65,65,45,1,False,506
1,2,Ivysaur,Grass,Poison,649,1137,60,62,63,80,80,60,1,False,649
2,3,Venusaur,Grass,Poison,849,1477,80,82,83,100,100,80,1,False,849
3,3,VenusaurMega Venusaur,Grass,Poison,985,1775,80,100,123,122,120,80,1,False,985
4,4,Charmander,Fire,NaN,491,838,39,52,43,60,50,65,1,False,491

### Saving our data

In [54]:
#df.to_csv('modified.csv',index=False) #It saves file without index
#df.to_excel('modified.excel',index=False)
df.to_csv('modified.txt',index=False,sep='\t') #text file

### Filtering data

In [55]:
df

,#,Name,Type 1,Type 2,Total1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total1
0,1,Bulbasaur,Grass,Poison,506,893,45,49,49,65,65,45,1,False,506
1,2,Ivysaur,Grass,Poison,649,1137,60,62,63,80,80,60,1,False,649
2,3,Venusaur,Grass,Poison,849,1477,80,82,83,100,100,80,1,False,849
3,3,VenusaurMega Venusaur,Grass,Poison,985,1775,80,100,123,122,120,80,1,False,985
4,4,Charmander,Fire,NaN,491,838,39,52,43,60,50,65,1,False,491
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,900,1700,50,100,150,100,150,50,6,True,900
796,719,DiancieMega Diancie,Rock,Fairy,1120,1980,50,160,110,160,110,110,6,True,1120
797,720,HoopaHoopa Confined,Psychic,Ghost,980,1720,80,110,60,150,130,70,6,True,980
798,720,HoopaHoopa Unbound,Psychic,Dark,1160,1990,80,160,60,170,130,80,6,True,1160
799,721,Volcanion,Fire,Water,980,1760,80,110,120,130,90,70,6,True,980

In [58]:
df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison')]

,#,Name,Type 1,Type 2,Total1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total1
0,1,Bulbasaur,Grass,Poison,506,893,45,49,49,65,65,45,1,False,506
1,2,Ivysaur,Grass,Poison,649,1137,60,62,63,80,80,60,1,False,649
2,3,Venusaur,Grass,Poison,849,1477,80,82,83,100,100,80,1,False,849
3,3,VenusaurMega Venusaur,Grass,Poison,985,1775,80,100,123,122,120,80,1,False,985
48,43,Oddish,Grass,Poison,510,930,45,50,55,75,65,30,1,False,510
49,44,Gloom,Grass,Poison,645,1155,60,65,70,85,75,40,1,False,645
50,45,Vileplume,Grass,Poison,800,1435,75,80,85,110,90,50,1,False,800
75,69,Bellsprout,Grass,Poison,550,915,50,75,35,70,30,40,1,False,550
76,70,Weepinbell,Grass,Poison,700,1170,65,90,50,85,45,55,1,False,700
77,71,Victreebel,Grass,Poison,860,1445,80,105,65,100,70,70,1,False,860
344,315,Roselia,Grass,Poison,620,1100,50,60,45,100,80,65,3,False,620
451,406,Budew,Grass,Poison,420,730,40,30,35,50,70,55,4,False,420
452,407,Roserade,Grass,Poison,775,1390,60,70,65,125,105,90,4,False,775
651,590,Foongus,Grass,Poison,542,921,69,55,45,55,55,15,5,False,542
652,591,Amoonguss,Grass,Poison,862,1451,114,85,70,85,80,30,5,False,862

In [66]:
new2=df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison')&(df['HP'] > 70)]

In [67]:
new2

,#,Name,Type 1,Type 2,Total1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total1
2,3,Venusaur,Grass,Poison,849,1477,80,82,83,100,100,80,1,False,849
3,3,VenusaurMega Venusaur,Grass,Poison,985,1775,80,100,123,122,120,80,1,False,985
50,45,Vileplume,Grass,Poison,800,1435,75,80,85,110,90,50,1,False,800
77,71,Victreebel,Grass,Poison,860,1445,80,105,65,100,70,70,1,False,860
652,591,Amoonguss,Grass,Poison,862,1451,114,85,70,85,80,30,5,False,862

<b>Reset Index</b>

In [69]:
new2.reset_index(drop=True)

,#,Name,Type 1,Type 2,Total1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total1
0,3,Venusaur,Grass,Poison,849,1477,80,82,83,100,100,80,1,False,849
1,3,VenusaurMega Venusaur,Grass,Poison,985,1775,80,100,123,122,120,80,1,False,985
2,45,Vileplume,Grass,Poison,800,1435,75,80,85,110,90,50,1,False,800
3,71,Victreebel,Grass,Poison,860,1445,80,105,65,100,70,70,1,False,860
4,591,Amoonguss,Grass,Poison,862,1451,114,85,70,85,80,30,5,False,862

<b>Regex filtering</b>

In [70]:
df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Total1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total1
3,3,VenusaurMega Venusaur,Grass,Poison,985,1775,80,100,123,122,120,80,1,False,985
7,6,CharizardMega Charizard X,Fire,Dragon,1050,1825,78,130,111,130,85,100,1,False,1050
8,6,CharizardMega Charizard Y,Fire,Flying,998,1769,78,104,78,159,115,100,1,False,998
12,9,BlastoiseMega Blastoise,Water,NaN,994,1801,79,103,120,135,115,78,1,False,994
19,15,BeedrillMega Beedrill,Bug,Poison,925,1330,65,150,40,15,80,145,1,False,925
23,18,PidgeotMega Pidgeot,Normal,Flying,905,1578,83,80,80,135,80,121,1,False,905
71,65,AlakazamMega Alakazam,Psychic,NaN,800,1480,55,50,65,175,95,150,1,False,800
87,80,SlowbroMega Slowbro,Water,Psychic,930,1800,95,75,180,130,80,30,1,False,930
102,94,GengarMega Gengar,Ghost,Poison,850,1570,60,65,80,170,95,130,1,False,850
124,115,KangaskhanMega Kangaskhan,Normal,NaN,1050,1700,105,125,100,60,100,100,1,False,1050
137,127,PinsirMega Pinsir,Bug,Flying,1040,1720,65,155,120,65,90,105,1,False,1040
141,130,GyaradosMega Gyarados,Water,Dark,1140,1878,95,155,109,70,130,81,1,False,1140
154,142,AerodactylMega Aerodactyl,Rock,Flying,1045,1665,80,135,85,70,95,150,1,False,1045
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,1372,2276,106,190,100,154,100,130,1,True,1372
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,1292,2196,106,150,70,194,120,140,1,True,1292
168,154,Meganium,Grass,NaN,849,1477,80,82,100,83,100,80,2,False,849
196,181,AmpharosMega Ampharos,Electric,Dragon,980,1815,90,95,105,165,110,45,2,False,980
224,208,SteelixMega Steelix,Steel,Ground,1010,1875,75,125,230,55,95,30,2,False,1010
229,212,ScizorMega Scizor,Bug,Steel,1040,1770,70,150,140,65,100,75,2,False,1040
232,214,HeracrossMega Heracross,Bug,Fighting,1130,1810,80,185,115,40,105,75,2,False,1130
248,229,HoundoomMega Houndoom,Dark,Fire,930,1645,75,90,90,140,90,115,2,False,930
268,248,TyranitarMega Tyranitar,Rock,Dark,1228,2102,100,164,150,95,120,71,2,False,1228
275,254,SceptileMega Sceptile,Grass,Dragon,990,1695,70,110,75,145,85,145,3,False,990
279,257,BlazikenMega Blaziken,Fire,Fighting,1110,1850,80,160,80,130,80,100,3,False,1110
283,260,SwampertMega Swampert,Water,Ground,1135,1905,100,150,110,95,110,70,3,False,1135
306,282,GardevoirMega Gardevoir,Psychic,Fairy,924,1672,68,85,65,165,135,100,3,False,924
327,302,SableyeMega Sableye,Dark,Ghost,750,1420,50,85,125,85,115,20,3,False,750
329,303,MawileMega Mawile,Steel,Fairy,790,1400,50,105,125,55,95,50,3,False,790
333,306,AggronMega Aggron,Steel,NaN,1050,1920,70,140,230,60,80,50,3,False,1050
336,308,MedichamMega Medicham,Fighting,Psychic,830,1405,60,100,85,80,85,100,3,False,830
339,310,ManectricMega Manectric,Electric,NaN,865,1520,70,75,80,135,80,135,3,False,865
349,319,SharpedoMega Sharpedo,Water,Dark,980,1615,70,140,70,110,65,105,3,False,980
354,323,CameruptMega Camerupt,Fire,Ground,940,1725,70,120,100,145,105,20,3,False,940
366,334,AltariaMega Altaria,Dragon,Fairy,960,1690,75,110,110,110,105,80,3,False,960
387,354,BanetteMega Banette,Ghost,NaN,1013,1661,64,165,75,93,83,75,3,False,1013
393,359,AbsolMega Absol,Dark,NaN,995,1620,65,150,60,115,60,115,3,False,995
397,362,GlalieMega Glalie,Ice,NaN,980,1660,80,120,80,120,80,100,3,False,980
409,373,SalamenceMega Salamence,Dragon,Flying,1180,2010,95,145,130,120,90,120,3,False,1180
413,376,MetagrossMega Metagross,Steel,Psychic,1150,1995,80,145,150,105,110,110,3,False,1150
418,380,LatiasMega Latias,Dragon,Psychic,1060,1910,80,100,120,140,150,110,3,True,1060
420,381,LatiosMega Latios,Dragon,Psychic,1120,1970,80,130,100,160,120,110,3,True,1120
426,384,RayquazaMega Rayquaza,Dragon,Flying,1350,2295,105,180,100,180,100,115,3,True,1350
476,428,LopunnyMega Lopunny,Normal,Fighting,982,1575,65,136,94,54,96,135,4,False,982
494,445,GarchompMega Garchomp,Dragon,Ground,1256,2099,108,170,115,120,95,92,4,False,1256
498,448,LucarioMega Lucario,Fighting,Steel,1055,1796,70,145,88,140,70,112,4,False,1055
511,460,AbomasnowMega Abomasnow,Grass,Ice,1038,1839,90,132,105,132,105,30,4,False,1038
527,475,GalladeMega Gallade,Psychic,Fighting,1084,1752,68,165,95,65,115,110,4,False,1084
591,531,AudinoMega Audino,Normal,Fairy,871,1572,103,60,126,80,126,50,5,False,871
796,719,DiancieMega Diancie,Rock,Fairy,1120,1980,50,160,110,160,110,110,6,True,1120

In [71]:
df.loc[~df['Name'].str.contains('Mega')] # Not contains

,#,Name,Type 1,Type 2,Total1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total1
0,1,Bulbasaur,Grass,Poison,506,893,45,49,49,65,65,45,1,False,506
1,2,Ivysaur,Grass,Poison,649,1137,60,62,63,80,80,60,1,False,649
2,3,Venusaur,Grass,Poison,849,1477,80,82,83,100,100,80,1,False,849
4,4,Charmander,Fire,NaN,491,838,39,52,43,60,50,65,1,False,491
5,5,Charmeleon,Fire,NaN,649,1112,58,64,58,80,65,80,1,False,649
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,1016,1723,108,100,121,81,95,95,6,True,1016
795,719,Diancie,Rock,Fairy,900,1700,50,100,150,100,150,50,6,True,900
797,720,HoopaHoopa Confined,Psychic,Ghost,980,1720,80,110,60,150,130,70,6,True,980
798,720,HoopaHoopa Unbound,Psychic,Dark,1160,1990,80,160,60,170,130,80,6,True,1160
799,721,Volcanion,Fire,Water,980,1760,80,110,120,130,90,70,6,True,980

In [76]:
import re
df.loc[df['Type 1'].str.contains('Fire|Grass',regex=True)]

,#,Name,Type 1,Type 2,Total1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total1
0,1,Bulbasaur,Grass,Poison,506,893,45,49,49,65,65,45,1,False,506
1,2,Ivysaur,Grass,Poison,649,1137,60,62,63,80,80,60,1,False,649
2,3,Venusaur,Grass,Poison,849,1477,80,82,83,100,100,80,1,False,849
3,3,VenusaurMega Venusaur,Grass,Poison,985,1775,80,100,123,122,120,80,1,False,985
4,4,Charmander,Fire,NaN,491,838,39,52,43,60,50,65,1,False,491
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,593,1021,62,50,58,73,54,72,6,False,593
736,668,Pyroar,Fire,Normal,815,1397,86,68,72,109,66,106,6,False,815
740,672,Skiddo,Grass,NaN,612,1020,66,65,48,62,57,52,6,False,612
741,673,Gogoat,Grass,NaN,977,1599,123,100,62,97,81,68,6,False,977
799,721,Volcanion,Fire,Water,980,1760,80,110,120,130,90,70,6,True,980

In [77]:
df.loc[df['Type 1'].str.contains('fire|grass',flags=re.I,regex=True)] #For any words whether capital or small

,#,Name,Type 1,Type 2,Total1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total1
0,1,Bulbasaur,Grass,Poison,506,893,45,49,49,65,65,45,1,False,506
1,2,Ivysaur,Grass,Poison,649,1137,60,62,63,80,80,60,1,False,649
2,3,Venusaur,Grass,Poison,849,1477,80,82,83,100,100,80,1,False,849
3,3,VenusaurMega Venusaur,Grass,Poison,985,1775,80,100,123,122,120,80,1,False,985
4,4,Charmander,Fire,NaN,491,838,39,52,43,60,50,65,1,False,491
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,593,1021,62,50,58,73,54,72,6,False,593
736,668,Pyroar,Fire,Normal,815,1397,86,68,72,109,66,106,6,False,815
740,672,Skiddo,Grass,NaN,612,1020,66,65,48,62,57,52,6,False,612
741,673,Gogoat,Grass,NaN,977,1599,123,100,62,97,81,68,6,False,977
799,721,Volcanion,Fire,Water,980,1760,80,110,120,130,90,70,6,True,980

In [79]:
df.loc[df['Name'].str.contains('^pi[a=z]*',flags=re.I,regex=True)]

,#,Name,Type 1,Type 2,Total1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total1
20,16,Pidgey,Normal,Flying,421,691,40,45,40,35,35,56,1,False,421
21,17,Pidgeotto,Normal,Flying,595,978,63,60,55,50,50,71,1,False,595
22,18,Pidgeot,Normal,Flying,805,1328,83,80,75,70,70,101,1,False,805
23,18,PidgeotMega Pidgeot,Normal,Flying,905,1578,83,80,80,135,80,121,1,False,905
30,25,Pikachu,Electric,NaN,500,820,35,55,40,50,50,90,1,False,500
136,127,Pinsir,Bug,NaN,880,1450,65,125,100,55,70,85,1,False,880
137,127,PinsirMega Pinsir,Bug,Flying,1040,1720,65,155,120,65,90,105,1,False,1040
186,172,Pichu,Electric,NaN,325,520,20,40,15,35,35,60,2,False,325
219,204,Pineco,Bug,NaN,520,920,50,65,90,35,35,15,2,False,520
239,221,Piloswine,Ice,Ground,850,1390,100,100,80,60,60,50,2,False,850
438,393,Piplup,Water,NaN,522,910,53,51,53,61,56,40,4,False,522
558,499,Pignite,Fire,Fighting,784,1272,90,93,55,70,55,55,5,False,784
578,519,Pidove,Normal,Flying,474,781,50,55,50,36,30,43,5,False,474

<b>Conditional Changes</b>

In [16]:
#df.loc[df['Type 1']=='Fire','Type 1'] ='Flamer'
df.loc[df['Type 1']=='Flamer','Type 1'] ='Fire'

In [17]:
df['Type 1'].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [18]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Type1
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,NaN
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,NaN
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,NaN
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,NaN
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Flamer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,NaN
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,NaN
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,NaN
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,NaN
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Flamer

In [19]:
df.loc[df['Type 1']=='Flamer','Legendary'] ='True'  #Legendary column value

In [20]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Type1
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,NaN
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,NaN
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,NaN
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,NaN
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Flamer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,NaN
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,NaN
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,NaN
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,NaN
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Flamer

In [22]:
df.drop(columns=['Type1'])

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [28]:
df.loc[df['Total'] < 500,['Generation','Legendary']]=['Test1','Test2']

In [29]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Type1
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,Test1,Test2,NaN
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,Test1,Test2,NaN
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,NaN
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,NaN
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,Test1,Test2,Flamer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,NaN
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,NaN
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,NaN
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,NaN
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Flamer

<b> Aggregate statistics (Group By)</b>

In [33]:
df.groupby(['Type 1']).mean()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
Type 1,,,,,,,,
Bug,334.492754,378.927536,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159
Dark,461.354839,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290
Dragon,474.375000,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250
Electric,363.500000,443.409091,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000
Fairy,449.529412,413.176471,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235
Fighting,363.851852,416.444444,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074
Fire,327.403846,458.076923,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308
Flying,677.750000,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000
Ghost,486.500000,439.562500,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750
Grass,344.871429,421.142857,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571
Ground,356.281250,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250
Ice,423.541667,433.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333
Normal,319.173469,401.683673,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020
Poison,251.785714,399.142857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429
Psychic,380.807018,475.947368,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228
Rock,392.727273,453.750000,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091
Steel,442.851852,487.703704,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259
Water,303.089286,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286

In [35]:
df.groupby(['Type 1']).mean().sort_values('Attack',ascending=False)

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
Type 1,,,,,,,,
Dragon,474.375000,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250
Fighting,363.851852,416.444444,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074
Ground,356.281250,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250
Rock,392.727273,453.750000,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091
Steel,442.851852,487.703704,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259
Dark,461.354839,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290
Fire,327.403846,458.076923,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308
Flying,677.750000,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000
Poison,251.785714,399.142857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429
Water,303.089286,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286
Ghost,486.500000,439.562500,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750
Normal,319.173469,401.683673,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020
Grass,344.871429,421.142857,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571
Ice,423.541667,433.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333
Psychic,380.807018,475.947368,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228
Bug,334.492754,378.927536,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159
Electric,363.500000,443.409091,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000
Fairy,449.529412,413.176471,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235

In [36]:
df.groupby(['Type 1']).sum()

              #  Total    HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
Type 1
Bug       23080  26146  3925    4897     4880     3717     4471   4256
Dark      14302  13818  2071    2740     2177     2314     2155   2361
Dragon    15180  17617  2666    3588     2764     3099     2843   2657
Electric  15994  19510  2631    3040     2917     3961     3243   3718
Fairy      7642   7024  1260    1046     1117     1335     1440    826
Fighting   9824  11244  1886    2613     1780     1434     1747   1784
Fire      17025  23820  3635    4408     3524     4627     3755   3871
Flying     2711   1940   283     315      265      377      290    410
Ghost     15568  14066  2062    2361     2598     2539     2447   2059
Grass     24141  29480  4709    5125     4956     5425     4930   4335
Ground    11401  14000  2361    3064     2715     1807     2008   2045
Ice       10165  10403  1728    1746     1714     1861     1831   1523
Normal    31279  39365  7573    7200     5865     5470     6245   7012
Poison     7050  11176  1883    2091     1927     1692     1803   1780
Psychic   21706  27129  4026    4073     3858     5609     4918   4645
Rock      17280  19965  2876    4086     4435     2787     3321   2460
Steel     11957  13168  1761    2503     3412     1823     2177   1492
Water     33946  48211  8071    8305     8170     8379     7898   7388

In [41]:
df['count']=1
df.groupby(['Type 1']).count()['count']

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: count, dtype: int64

<b> Working with large amount of data</b>

In [46]:
#Read data in chunksize which means Rows

pd.read_csv(r'pokemon.csv',chunksize=5)

In [48]:
new_df=pd.DataFrame(columns=df.columns)

In [ ]:
new_df = pd.concat([new_df,results])